# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EQradXb5IzrZgvhmsQfEGeJpmBamMuqz
"""

#ex1
radius = float(input("Enter circle radius: "))
print(3.14 * radius**2)

#ex2
C = float(input("Enter the temperature in Celsius: "))
F = (C * 1.8) + 32
print(f"Temperature in Fahrenheit is: {F}")

#ex3
number = int(input("Enter a number: "))
is_prime = True
if number < 2:
  print(f"{number} is a prime number")
else:
  for i in range(2, number):
    if number % i == 0:
      is_prime = False
      break
if is_prime:
  print(f"{number} is a prime number")
else:
  print(f"{number} is NOT a prime number")

#ex4
number = int(input("Enter a number: "))
sum = 0
is_perfect = True
if number == 1:
  print(f"{number} is a perfect number")
else:
  for i in range(1, number):
    remainder = number % i
    if remainder == 0:
      sum = sum + i
if sum != number:
  is_perfect = False
if is_perfect:
  print(f"{number} is a perfect number")
else:
  print(f"{number} is NOT a perfect number")

#ex5
color = str(input("Enter a color: "))
list = ("red", "green", "white", "black", "yellow")
in_list = color in list
if in_list:
  print(f"{color} is in the list")
else:
  print(f"{color} is NOT in the list")

#ex6
def range1():
  for i in range(0, 7):
    print(i)
def range2():
  for i in range(1, 11, 3):
    print(i)
def range3():
  for i in range(5, 0, -1):
    print(i)
def range4():
  for i in range(6, -3, -2):
    print(i)
range1()
range2()
range3()
range4()

#ex7
s = input("Enter a price: ")
print(s.replace("$", ""))

#ex8
def extract_even():
  even_I = []
  I = []
  i = int(input("How many number you want to enter? "))
  for y in range(1, i+1):
    I.append(int(input("Enter a number: ")))
  for x in I:
    e = x % 2
    if e == 0:
      even_I.append(x)
  print(even_I)
extract_even()

#ex9
def factorial():
  n = int(input("Enter a number: "))
  t = 1
  for i in range(0, n):
    t = t * (n - i)
  print(t)
factorial()

#ex10
n = int(input("Enter a number: "))
u = []
for i in range(1, n+1):
  r = n % i
  if r == 0:
    u.append(i)
print(u)

#ex11
x1 = float(input("Enter x1: "))
y1 = float(input("Enter y1: "))
x2 = float(input("Enter x2: "))
y2 = float(input("Enter y2: "))
distance = ((x2 - x1)**2 + (y2 - y1)**2)**0.5
print(distance)

#ex12
def pattern():
  m = int(input("Enter m: "))
  n = int(input("Enter n: "))
  for i in range(m):
    for j in range(n):
      if i == 0 or i == m-1 or j == 0 or j == n-1:
        print("*", end="  ")
      else:
        print(" ", end="  ")
    print()
pattern()
